### PR TITLE
Front page prototype

### PR DESCRIPTION
**Pull request by bohuim**
Prototype hosted at [aid-berkeley.surge.sh](http://aid-berkeley.surge.sh)

- Project settings
    - Update: `react-helmet ~> v5.0.3`
    - New: `babel-plugin-root-import`
        - `package.json` updated to include babel config with this plugin
    - New: npm script `surge` that defaults to `aid-berkeley.surge.sh`
        - Unsure if anyone else can push to this domain, I may need to hand out permissions.
- File hierarchy
    - New: `~/pages/assets` with `./images` inside
    - New: `~/pages/components` includes React components that are not full pages
    - New: `~/styles` for all styles `css|scss|sass|less`
         - Moved all style files into it
- Front page
    - Integrated @erikyangs navbar
       - Added some animation to it
    - Landing header with title, tinted banner image, and learn more button
    - About description
    - Action cards (dummy texts)
    - People section with no content

- TODO
    - People section + the other pages
    - Hook up `react-router` to all the links
    - Make React components pull data from client set config files `~/content` or something, instead of hard coding into source files
    - If we're going to sticky the navbar, it needs to turn black once scrolled past header
    - **MOBILE FIRST?**

### CODE REVIEW

**Comment by dav1dn** [comment]
> New: ~/pages/components includes React components that are not full pages

Reposting here for posterity: should we mess w/ Gatsby to avoid having it build from this directory (should just be a matter of adding an `exclude:` to the loader, or just have ~/components/ instead?

**Comment by bohuim** [comment]
I think changing the config to actually exclude `~pages/components` is definitely better/cleaner in long-term, but I don't think it's a priority at this point.

**Comment by bohuim** [comment]
Moved out components to `~/components` and updated files accordingly.
Plus some other minor fixes, refer to commit.

**Review by dav1dn — APPROVED** [review]
lgtm, merging in the interest of having our folder structures merged

**Pull request merged**
